import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, ReferenceLine, Label } from "recharts";

const timelineData = [
  { time: "1:00", value: 8 },
  { time: "1:15", value: 14 },
  { time: "1:30", value: 22 },
  { time: "1:45", value: 18 },
  { time: "2:00", value: 26 },
  { time: "2:15", value: 34 },
  { time: "2:30", value: 28 },
  { time: "2:45", value: 20 },
  { time: "3:00", value: 10 },
];

const peakIndex = 5; // 2:15 PM

const AdminReport = () => {
  return (
    <div className="min-h-screen bg-card">
      <div className="max-w-[768px] mx-auto px-8 py-8">
        {/* Report Header */}
        <p className="text-sm font-medium text-primary-600 text-center">Who Else Is Here</p>
        <p className="text-xs text-gray-400 text-center mt-1">Post-Event Report</p>
        <div className="border-t border-gray-200 my-4" />

        {/* Event Info */}
        <h1 className="text-2xl font-bold text-gray-900 text-center">RUMC Job Networking</h1>
        <p className="text-base text-gray-600 text-center mt-1">Career Quest Workshop · Room 101</p>
        <p className="text-sm text-gray-400 text-center mt-1">March 8, 2026 · 1:00 PM – 3:00 PM</p>

        {/* Headline Metrics */}
        <div className="grid grid-cols-3 gap-4 mt-8">
          {[
            { value: "38", label: "Attendees" },
            { value: "127", label: "LinkedIn Connections Facilitated" },
            { value: "69%", label: "Activation Rate" },
          ].map((m) => (
            <div key={m.label} className="bg-gray-50 rounded-lg p-6 text-center">
              <p className="text-3xl font-bold text-gray-900">{m.value}</p>
              <p className="text-sm text-gray-600 mt-1">{m.label}</p>
            </div>
          ))}
        </div>

        {/* Context Bar */}
        <p className="text-sm text-gray-600 text-center italic mt-4">
          69% of attendees actively networked through the platform. Industry average for event networking tools: 15–25%.
        </p>

        {/* Activity Summary */}
        <section className="mt-6">
          <h2 className="text-base font-semibold text-gray-900">Activity Summary</h2>
          <div className="flex flex-col gap-2 mt-3">
            {[
              "Peak networking activity: 2:15 PM",
              "Most active period: during the afternoon break",
              "Average LinkedIn taps per attendee: 3.3",
              "Attendees who returned post-event: 12 (32%)",
            ].map((item) => (
              <p key={item} className="text-sm text-gray-700">{item}</p>
            ))}
          </div>
        </section>

        {/* Activity Timeline */}
        <section className="mt-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Activity Timeline</h2>
          <div className="h-[240px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={timelineData} margin={{ top: 20, right: 8, left: -16, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(220 13% 91%)" />
                <XAxis dataKey="time" tick={{ fontSize: 12, fill: "hsl(218 11% 65%)" }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 12, fill: "hsl(218 11% 65%)" }} axisLine={false} tickLine={false} />
                <Tooltip />
                <ReferenceLine x="2:15" stroke="hsl(218 11% 65%)" strokeDasharray="3 3">
                  <Label value="Peak" position="top" fontSize={11} fill="hsl(218 11% 65%)" />
                </ReferenceLine>
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {timelineData.map((_, i) => (
                    <Cell key={i} fill={i === peakIndex ? "hsl(239 84% 67%)" : "hsl(239 84% 67% / 0.6)"} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </section>

        {/* Footer */}
        <div className="mt-8">
          <div className="border-t border-gray-200 my-4" />
          <p className="text-xs text-gray-400 text-center">Generated by Who Else Is Here · whoelseishere.com</p>
          <p className="text-xs text-gray-400 text-center mt-1">Report generated: March 8, 2026 at 4:30 PM</p>
        </div>
      </div>
    </div>
  );
};

export default AdminReport;
